//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica_elecciones.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PruebaTecnicaContexto : DbContext
    {
        public PruebaTecnicaContexto()
            : base("name=PruebaTecnicaContexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Partido> Partido { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<ResultdoElectoral> ResultdoElectoral { get; set; }
    }
}
