//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTecnica_elecciones.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultdoElectoral
    {
        public int IdRE { get; set; }
        public string PorcentajeElectoral { get; set; }
        public Nullable<int> cantidadVotos { get; set; }
        public Nullable<int> ProvinciaPerteneciente { get; set; }
        public Nullable<int> PartidoPerteneciente { get; set; }
    
        public virtual Partido Partido { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
